services:
  - type: web
    name: civic-scam-shield-api
    runtime: docker
    rootDir: Chaitanya_Backend
    dockerfilePath: ./Dockerfile
    envVars:
      - key: GEMINI_API_KEY
        sync: false
    plan: free
